form = {
  'work_table': 'group2admin',
  'work_table_id': 'group_id',
  'title': 'Группы',
  'header_field': 'name',
  'default_find_filter': 'name',
  'make_delete': 0,
  'read_only': 1,
  'not_create': 1,
  'tree_use': 0,
  'fields': [
    {
      'description': 'Название',
      'type': 'text',
      'name': 'name',
      'filter_on': True,
    },
    {
      'description': 'Члены группы',
      'name': 'users',
      'type': '1_to_m',
      'table': 'admin_group',
      'table_id': 'admin_group_id',
      'foreign_key': 'group_id',
      'fields': [
        {
          'description': 'Админ',
          'name': 'admin_id',
          'type': 'select_from_table',
          'table': 'admin',
          'value_field': 'admin_id',
          'header_field': 'login',
        },
      ],
    },
    {
      'description': 'Меню для группы',
      'name': 'menus',
      'type': '1_to_m',
      'table': 'permission',
      'table_id': 'permision_id',
      'foreign_key': 'id',
      'sort': 1,
      'fields': [
        {
          'description': 'Пункт',
          'name': 'menu_id',
          'type': 'select_from_table',
          'table': 'admin_menu',
          'value_field': 'id',
          'header_field': 'name',
          'sort': 1,
        },
        {
          'description': 'Тип',
          'name': 'type',
          'type': 'text',
          'hide': True,
          'value': 2,
        },
        {
          'description': 'Разрешено',
          'name': 'allowed',
          'type': 'checkbox',
          'value': 1,
          'change_in_slide': 1,
        },
      ],
    },
  ],
}
