form={
  'work_table':'template',
  'work_table_id':'template_id',
  'title':'Шаблоны',
  'make_delete':0,
  'read_only':1,
  'tree_use':0,
  'default_find_filter':'header',
  'header_field':'header',
  'QUERY_SEARCH_TABLES':[
    {'t':'template','a':'wt'},
    {'t':'domain','a':'d','l':'d.template_id=wt.template_id','lj':1},
    {'t':'project','a':'p','l':'d.project_id=p.project_id'},
  ],
  'fields':[
    {
      'description':'Домен',
      'type':'filter_extend_text',
      'name':'domain',
      'filter_table':'domain',
      'tablename':'d',
      'header_field':'domain',
      'value_field':'domain_id',
      'db_name':'domain',
      'autocomplete':True,
      'read_only':True,
      'make_delete':0,
      'filter_on':True,
    },
    {
      'description':'Наименование шаблона',
      'type':'text',
      'name':'header',
      'regexp_rules':[
        '/^.+$/','Поле обязательно для заполнения',
      ],
      'read_only':True,
      'filter_on':True,
    },
    {
      'description':'Папка с шаблонами',
      'type':'text',
      'name':'folder',
      'read_only':True,
    },
    {
      'description':'Не Кешировать nginx-ом',
      'add_description':'Изменения вступают в силу в течении 30 минут.',
      'type':'checkbox',
      'name':'not_cache_nginx',
      'filter_on':True,
    },
  ],
}
