form={
  'work_table':'work_types',
  'work_table_id':'id',
  'title':'Виды работы',
  'make_delete':1,
  'default_find_filter':'header',
  'header_field':'header',
  'fields':[
    {
      'description':'Название',
      'type':'text',
      'name':'header',
      'filter_on':True,
    },
    {
      'description':'Коэффициенты',
      'name':'coefs',
      'type':'1_to_m',
      'table':'work_type_coef',
      'table_id':'id',
      'foreign_key':'work_type_id',
      'fields':[
        {
          'description':'Дата',
          'name':'added',
          'type':'date',
        },
        {
          'description':'Должность',
          'name':'post',
          'type':'select_values',
          'values':[
            {'v':1,'d':'Программист'},
            {'v':2,'d':'Менеджер'},
            {'v':3,'d':'Верстальщик'},
            {'v':4,'d':'Дизайнер'},
            {'v':5,'d':'Копирайтер'},
            {'v':6,'d':'Контентщик'},
          ],
        },
        {
          'description':'Пользователь',
          'name':'user_id',
          'type':'select_from_table',
          'table':'workers',
          'value_field':'id',
          'header_field':'fio',
        },
        {
          'description':'Коэффициент',
          'name':'value',
          'type':'text',
        },
      ],
    },
  ],
}
