form={
  'work_table':'project_hosting',
  'work_table_id':'id',
  'title':'Хостинги проекта',
  'make_delete':1,
  'default_find_filter':'header',
  'header_field':'header',
  'QUERY_SEARCH_TABLES':[
    {'t':'project_hosting','a':'wt'},
    {'t':'domain','a':'d','l':'d.domain_id=wt.domain_id','lj':1},
    {'t':'template','a':'t','l':'d.template_id=t.template_id','lj':1},
    {'t':'project','a':'p','l':'p.project_id=d.project_id','lj':1},
  ],
  'cols':[
    [
      {'description':'Ссылки','name':'links'},
    ],
    [
      {'description':'Общая информация','name':'info'},
    ],
  ],
  'fields':[
    {
      'description':'Проект №',
      'type':'filter_extend_text',
      'name':'project_id',
      'tablename':'p',
      'db_name':'project_id',
      'filter_type':'range',
      'tab':'links',
    },
    {
      'description':'Домен',
      'type':'select_from_table',
      'name':'domain_id',
      'table':'domain',
      'header_field':'domain',
      'value_field':'domain_id',
      'tablename':'d',
      'autocomplete':True,
      'tab':'info',
    },
    {
      'description':'Домен (поиск)',
      'type':'filter_extend_text',
      'name':'f_domain',
      'tablename':'d',
      'db_name':'domain',
      'autocomplete':True,
      'tab':'info',
    },
    {'description':'Тестовый домен','type':'text','name':'testdomain','tab':'info'},
    {'description':'Папки для проверки размера хостинга','add_description':'Больше одной через ;','type':'text','name':'template_folders','tab':'info'},
    {
      'description':'Размер папки files, Мб',
      'type':'text',
      'name':'size_project',
      'read_only':True,
      'filter_type':'range',
      'tab':'info',
    },
    {
      'description':'Размер папки templates, Мб',
      'type':'text',
      'name':'size_template',
      'read_only':True,
      'filter_type':'range',
      'tab':'info',
    },
    {'description':'Название','type':'text','name':'header','filter_on':True,'tab':'info'},
    {'description':'Дата создания','type':'date','name':'born_date','tab':'info'},
    {'description':'Хостинг оплачен до','type':'date','name':'hosting_paid_to','tab':'info'},
    {
      'description':'Шаблон',
      'type':'filter_extend_select_from_table',
      'name':'template_id',
      'table':'template',
      'value_field':'template_id',
      'header_field':'header',
      'db_name':'template_id',
      'autocomplete':True,
      'tab':'info',
    },
    {
      'description':'Тип сайта',
      'type':'select_values',
      'name':'site_type',
      'values':[
        {'v':1,'d':'клиентский сайт'},
        {'v':2,'d':'новые СЭЛТы'},
        {'v':3,'d':'старые СЭЛТы'},
        {'v':5,'d':'моб приложение'},
        {'v':4,'d':'другое'},
      ],
      'tab':'info',
    },
    {'description':'Отключен','type':'checkbox','name':'disabled','filter_on':True,'tab':'info'},
    {'description':'Хостинг клиента','type':'checkbox','name':'client_hosting','tab':'info'},
    {
      'description':'Стоимость хостинга в год',
      'type':'text',
      'name':'paid_on_year',
      'filter_type':'range',
      'read_only':True,
      'tab':'info',
    },
    {
      'description':'ID CRM strateg',
      'type':'filter_extend_text',
      'name':'user_id',
      'tablename':'d',
      'db_name':'user_id',
      'read_only':True,
      'tab':'info',
    },
    {'description':'Комментарий','type':'textarea','name':'comment','tab':'info'},
  ],
}
