form={
  'work_table':'workers',
  'work_table_id':'id',
  'title':'Сотрудники',
  'make_delete':0,
  'read_only':1,
  'not_create':1,
  'tree_use':0,
  'default_find_filter':'fio',
  'fields':[
    {
      'description':'ФИО',
      'type':'text',
      'name':'fio',
      'filter_on':True,
    },
    {
      'description':'Логин',
      'type':'text',
      'name':'login',
    },
    {
      'description':'Должность',
      'type':'select_values',
      'name':'post',
      'values':[
        {'v':1,'d':'Программист'},
        {'v':2,'d':'Менеджер'},
        {'v':3,'d':'Верстальщик'},
        {'v':4,'d':'Дизайнер'},
        {'v':5,'d':'Копирайтер'},
        {'v':6,'d':'Контентщик'},
      ],
    },
    {
      'description':'Оклад',
      'type':'text',
      'name':'oklad',
      'regexp_rules':[
        '/^\\d+(\\.\\d+)?$/','Оклад должен быть числом',
      ],
    },
    {
      'description':'Оклады',
      'type':'1_to_m',
      'name':'oklads',
      'read_only':0,
      'table':'worker_oklads',
      'table_id':'id',
      'foreign_key':'user_id',
      'fields':[
        {
          'description':'Оклад',
          'name':'value',
          'type':'text',
        },
        {
          'description':'Изменён',
          'name':'added',
          'type':'date',
        },
      ],
    },
    {
      'description':'План',
      'type':'text',
      'name':'plan',
      'regexp_rules':[
        '/^\\d+(\\.\\d+)?$/','План должен быть числом',
      ],
    },
    {
      'description':'Планы',
      'type':'1_to_m',
      'name':'plans',
      'table':'worker_plan',
      'table_id':'id',
      'foreign_key':'user_id',
      'fields':[
        {
          'description':'План',
          'name':'value',
          'type':'text',
        },
        {
          'description':'Изменён',
          'name':'added',
          'type':'date',
        },
      ],
    },
    {
      'description':'Процент',
      'type':'text',
      'name':'percent',
    },
    {
      'description':'Проценты',
      'type':'1_to_m',
      'name':'percents',
      'table':'worker_percent',
      'table_id':'id',
      'foreign_key':'user_id',
      'fields':[
        {
          'description':'Процент',
          'name':'value',
          'type':'text',
        },
        {
          'description':'Изменён',
          'name':'added',
          'type':'date',
        },
      ],
    },
    {
      'description':'Стоимость "Главная"',
      'type':'text',
      'name':'price_main_page',
    },
    {
      'description':'Стоимость "Внутренняя"',
      'type':'text',
      'name':'price_in_page',
    },
    {
      'description':'Стоимость "Наполнение(1 стр)"',
      'type':'text',
      'name':'price_per_page',
    },
    {
      'description':'Стоимость "1000 знаков"',
      'type':'text',
      'name':'price_symbol',
    },
    {
      'description':'Удалённо',
      'type':'checkbox',
      'name':'remote',
    },
    {
      'description':'Вкл',
      'type':'checkbox',
      'name':'enabled',
      'value':1,
      'filter_on':True,
    },
    {
      'description':'Не учитывать бонусы в мотивацию',
      'type':'checkbox',
      'name':'bonus',
    },
  ],
}
