form={
    'work_table':'good',
    'work_table_id':'id',
    'title':'Товары',
    'sort':False,
    'tree_use':False,
    #'explain':1,
    'header_field':'url',
    'default_find_filter':'header',
    'QUERY_SEARCH_TABLES':[
        {'t':'good','a':'wt'},
        {'t':'category','a':'c','l':'c.id=wt.category_id','lj':1,},
        {'t':'color','a':'color','l':'color.id=wt.color_id','lj':1,'for_fields':['color_id']},
        {'t':'model','a':'model','l':'model.id=wt.model_id','lj':1,'for_fields':['model_id']},
        {'t':'season','a':'season','l':'season.id=wt.season_id','lj':1,'for_fields':['season_id']},
    ],
    'GROUP_BY':'wt.id',
    'fields': [ 
        {
            'description':'Название',
            'type':'text',
            'name':'header',
            'filter_on':True
        },
        {
            'description':'Категория',
            'type':'select_from_table',
            'table':'category',
            'name':'category_id',
            'tablename':'c',
            'header_field':'header',
            'value_field':'id',
            'filter_on':True
        },
        {
            'description':'Артикул',
            'type':'text',
            'name':'artikul',
            'filter_on':True
        },
        {
            'description':'Цена',
            'type':'text',
            'name':'price',
            'filter_on':True
        },
        {
            'description':'Фотогалерея',
            'type':'1_to_m',
            'name':'photos',
            'table':'good_galery',
            'table_id':'id',
            'foreign_key':'good_id',
            'sort':1,
            'fields':[
                {
                    'description':'Фото',
                    'preview':1,
                    'type':'file',
                    'name':'photo',
                    'filedir':'./files/good_galery',
                    'preview':'300x300',
                    'resize':[
                        {
                            'description':'Для спика товаров',
                            'file':'<%filename_without_ext%>_mini1.<%ext%>',
                            'size':'300x300',
                            'quality':'100'
                        },
                        {
                            'description':'Для карточек товара',
                            'file':'<%filename_without_ext%>_mini2.<%ext%>',
                            'size':'585x585',
                            'quality':'100'
                        },
                    ]
                }
            ],
            'filter_on':False
        },
        {
            'description':'Новинка',
            'name':'new',
            'type':'checkbox'
        },
        {
            'description':'ТОП',
            'name':'top',
            'type':'checkbox'
        },
        {
            'description':'Распродажа',
            'name':'sale',
            'type':'checkbox'
        },
        {
            'description':'Цвет',
            'name':'color_id',
            'table':'color',
            'tablename':'color',
            'type':'select_from_table',
            'header_field':'header',
            'value_field':'id',
            #'filter_code':lambda form,field,row: row['color__header']
        },
        {
            'description':'Модель',
            'name':'model_id',
            'table':'model',
            'tablename':'model',
            'type':'select_from_table',
            'header_field':'header',
            'value_field':'id',
        },
        {
            'description':'Сезон',
            'name':'season_id',
            'table':'season',
            'tablename':'season',
            'type':'select_from_table',
            'header_field':'header',
            'value_field':'id',
        },
        {
            'description':'Год',
            'name':'year',
            'type':'text',
            'regexp_rules':[
                '^\d{4}$','укажите год, например 2024'
            ],
            'make_change_in_search':1,
            'filter_on':1,

        },
        {
            'description':'Параметры',
            'type':'1_to_m',
            'name':'params',
            'table':'good_param',
            'table_id':'id',
            'foreign_key':'good_id',
            'sort':1,
            'fields':[
                {
                    'description':'параметр',
                    'type':'text',
                    'name':'header',
                },
                {
                    'description':'Значение',
                    'type':'text',
                    'name':'value',
                },
            ],
        },
        {
            'description':'Описание',
            'type':'wysiwyg',
            'name':'description',
            'filter_on':False
        },

  ]  
    
}
      


