form={
  'work_table':'project_1_comp',
  'work_table_id':'project_1_comp_id',
  'title':'Компании',
  'make_delete':0,
  'read_only':1,
  'tree_use':0,
  'default_find_filter':'firm',
  'header_field':'header',
  'fields':[
    {
      'description':'Login',
      'type':'text',
      'name':'login',
    },
    {
      'description':'password',
      'type':'password',
      'name':'password',
    },
    {
      'description':'Название компании',
      'type':'text',
      'name':'firm',
      'filter_on':True,
    },
    {
      'description':'Телефон',
      'type':'text',
      'name':'phone',
    },
    {
      'description':'Факс',
      'type':'text',
      'name':'fax',
    },
    {
      'description':'Сайт',
      'type':'text',
      'name':'web',
    },
    {
      'description':'Email',
      'type':'text',
      'name':'email',
    },
    {
      'description':'ФИО',
      'type':'text',
      'name':'fio',
    },
    {
      'description':'Адрес',
      'type':'text',
      'name':'address',
    },
    {
      'description':'Дополнительно',
      'type':'textarea',
      'name':'more',
    },
    {
      'description':'Регион',
      'type':'select_from_table',
      'name':'region_id',
      'table':'struct_1_region',
      'header_field':'header',
      'value_field':'struct_1_region_id',
    },
  ],
}
