form={
  'work_table':'adm_client',
  'work_table_id':'id',
  'title':'Клиенты',
  'default_find_filter':'fio',
  'fields':[
    {'description':'ФИО','type':'text','name':'fio','filter_on':True},
    {'description':'Email','type':'text','name':'email','filter_on':True},
    {'description':'Телефон','type':'text','name':'phone','filter_on':True},
    {'description':'ICQ','type':'text','name':'icq'},
    {'description':'Skype','type':'text','name':'skype'},
    {'description':'Баланс','type':'text','name':'balance','read_only':True},
    {
      'description':'Платежи клиента',
      'name':'client_add_balance',
      'type':'1_to_m',
      'table':'adm_client_add_balance',
      'table_id':'id',
      'foreign_key':'client_id',
      'fields':[
        {'description':'Сумма','name':'price','type':'text'},
        {'description':'Зачислить на баланс','name':'add_to_balance','type':'checkbox'},
        {'description':'Заголовок','name':'header','type':'text'},
        {'description':'Дата оплаты','name':'paid_date','type':'date'},
        {
          'description':'Кошелёк',
          'name':'purse_id',
          'type':'select_from_table',
          'table':'adm_purse',
          'value_field':'id',
          'header_field':'header',
        },
      ],
    },
    {
      'description':'Услуги клиенту',
      'name':'client_service',
      'type':'1_to_m',
      'table':'adm_client_service',
      'table_id':'id',
      'foreign_key':'client_id',
      'fields':[
        {'description':'Заголовок','name':'header','type':'text'},
        {
          'description':'Услуга',
          'name':'service_id',
          'type':'select_from_table',
          'table':'adm_service',
          'value_field':'id',
          'header_field':'header',
        },
        {'description':'Дата начала','name':'begin_dat','type':'date'},
      ],
    },
  ],
}
