# Левое меню бэкендера для проекта 5837 (CMS-конструктор t1).
# Плоский список всех сущностей проекта. Кнопка = переход в admin-tree
# (дерево) или admin-table (список) с параметром config.
left_menu = [
    {
        'description': 'Каталог',
        'value': 'admin-tree',
        'type': 'vue',
        'icon': 'fa fa-sitemap',
        'params': {'config': 'ds_catalog'},
    },
    {
        'description': 'Товары',
        'value': 'admin-table',
        'type': 'vue',
        'icon': 'fa fa-cube',
        'params': {'config': 'ds_good'},
    },
    {
        'description': 'Справочник характеристик',
        'value': 'admin-table',
        'type': 'vue',
        'icon': 'fa fa-list-alt',
        'params': {'config': 'ds_params'},
    },
    {
        'description': 'Бренды',
        'value': 'admin-table',
        'type': 'vue',
        'icon': 'fa fa-trademark',
        'params': {'config': 'ds_brands'},
    },
    {
        'description': 'Новости',
        'value': 'admin-table',
        'type': 'vue',
        'icon': 'fa fa-newspaper',
        'params': {'config': 'ds_news'},
    },
    {
        'description': 'Статьи',
        'value': 'admin-table',
        'type': 'vue',
        'icon': 'fa fa-file-alt',
        'params': {'config': 'ds_article'},
    },
    {
        'description': 'Услуги',
        'value': 'admin-tree',
        'type': 'vue',
        'icon': 'fa fa-wrench',
        'params': {'config': 'ds_service'},
    },
    {
        'description': 'Слайдер',
        'value': 'admin-tree',
        'type': 'vue',
        'icon': 'fa fa-image',
        'params': {'config': 'ds_slider'},
    },
    {
        'description': 'Сертификаты',
        'value': 'admin-tree',
        'type': 'vue',
        'icon': 'fa fa-certificate',
        'params': {'config': 'ds_certificates'},
    },
    {
        'description': 'Команда',
        'value': 'admin-tree',
        'type': 'vue',
        'icon': 'fa fa-users',
        'params': {'config': 'ds_employee'},
    },
    {
        'description': 'Галерея',
        'value': 'admin-tree',
        'type': 'vue',
        'icon': 'fa fa-images',
        'params': {'config': 'ds_galery'},
    },
    {
        'description': 'Видео',
        'value': 'admin-tree',
        'type': 'vue',
        'icon': 'fa fa-video',
        'params': {'config': 'ds_video'},
    },
    {
        'description': 'Отзывы',
        'value': 'admin-tree',
        'type': 'vue',
        'icon': 'fa fa-comments',
        'params': {'config': 'ds_reviews'},
    },
    {
        'description': 'Преимущества',
        'value': 'admin-tree',
        'type': 'vue',
        'icon': 'fa fa-star',
        'params': {'config': 'ds_advantages'},
    },
    {
        'description': 'Клиенты',
        'value': 'admin-tree',
        'type': 'vue',
        'icon': 'fa fa-handshake',
        'params': {'config': 'ds_clients'},
    },
    {
        'description': 'Документы',
        'value': 'admin-tree',
        'type': 'vue',
        'icon': 'fa fa-paperclip',
        'params': {'config': 'ds_doc'},
    },
    {
        'description': 'Заявки с сайта',
        'value': 'admin-table',
        'type': 'vue',
        'icon': 'fa fa-envelope',
        'params': {'config': 'ds_form_submit'},
    },
    {
        'description': 'Заказы',
        'value': 'admin-table',
        'type': 'vue',
        'icon': 'fa fa-shopping-cart',
        'params': {'config': 'ds_zakaz'},
    },
    {
        'description': 'Статичные страницы',
        'value': 'admin-table',
        'type': 'vue',
        'icon': 'fa fa-file',
        'params': {'config': 'ds_text'},
    },
    {
        'description': 'Верхнее меню',
        'value': 'admin-tree',
        'type': 'vue',
        'icon': 'fa fa-bars',
        'params': {'config': 'ds_top_menu'},
    },
    {
        'description': 'Нижнее меню',
        'value': 'admin-tree',
        'type': 'vue',
        'icon': 'fa fa-grip-lines',
        'params': {'config': 'ds_bottom_menu'},
    },
    {
        'description': 'Настройки',
        'value': 'const',
        'type': 'vue',
        'icon': 'fa fa-wrench',
        'params': {'config': 'template_const'},
    },
]