form={
  'work_table':'landing_block',
  'work_table_id':'id',
  'title':'Настройки блока для лендинга',
  'make_delete':0,
  'read_only':0,
  'sort':True,
  'sort_field':'sort',
  'default_find_filter':'header',
  'header_field':'header',
  'foreign_key':'template_id',
  'fields':[
    {
      'description':'Шаблон',
      'type':'select_from_table',
      'name':'template_id',
      'table':'template',
      'value_field':'template_id',
      'header_field':'header',
      'autocomplete':1,
      'read_only':True,
    },
    {
      'description':'Тип блока',
      'type':'select_from_table',
      'name':'type',
      'table':'landing_block_type',
      'value_field':'id',
      'header_field':'header',
      'sort':True,
      'regexp_rules':['^[0-9]+$','Выберите тип блока'],
    },
    {
      'description':'Название блока в админке сайта',
      'type':'text',
      'name':'header',
      'regexp_rules':['^.+$','Заполните название блока'],
    },
    {
      'description':'Опции блока',
      'type':'multiconnect',
      'name':'opt',
      'relation_table':'landing_block_options',
      'relation_table_header':'header',
      'relation_table_id':'id',
      'order':'sort',
      'relation_save_table':'landing_block_tmpl_opt',
      'relation_save_table_id_relation':'landing_block_options_id',
      'relation_save_table_id_worktable':'landing_block_id',
    },
    {
      'description':'Доп. описания переменных блока',
      'type':'1_to_m',
      'name':'block_subvars',
      'table':'landing_block_subvars',
      'table_id':'id',
      'foreign_key':'landing_block_id',
      'fields':[
        {
          'description':'Переменная',
          'type':'select_from_table',
          'name':'opt_sub_id',
          'table':'landing_block_options_sub',
          'header_field':'concat(header," - ",name)',
          'value_field':'id',
          'order':'sort',
          'regexp_rules':['^[0-9]+$','Выберите переменную'],
        },
        {
          'description':'Описание поля',
          'type':'codelist',
          'name':'body',
        },
      ],
    },
  ],
}
