form = {
  'work_table': 'admin',
  'work_table_id': 'admin_id',
  'title': 'Админы',
  'header_field': 'login',
  'default_find_filter': 'login',
  'make_delete': 0,
  'read_only': 1,
  'not_create': 1,
  'tree_use': 0,
  'fields': [
    {
      'description': 'Активен',
      'type': 'checkbox',
      'name': 'enabled',
      'value': 1,
      'filter_on': True,
    },
    {
      'description': 'Логин',
      'type': 'text',
      'name': 'login',
      'filter_on': True,
    },
    {
      'description': 'E-mail',
      'type': 'text',
      'name': 'email',
      'filter_on': True,
    },
    {
      'description': 'Пароль',
      'type': 'password',
      'name': 'password',
    },
    {
      'description': 'Принадлежность к группам',
      'name': 'groups',
      'type': '1_to_m',
      'table': 'admin_group',
      'table_id': 'admin_group_id',
      'foreign_key': 'admin_id',
      'fields': [
        {
          'description': 'Группа',
          'name': 'group_id',
          'type': 'select_from_table',
          'table': 'group2admin',
          'value_field': 'group_id',
          'header_field': 'name',
        },
      ],
    },
    {
      'description': 'Меню для пользователя',
      'name': 'menus',
      'type': '1_to_m',
      'table': 'permission',
      'table_id': 'permision_id',
      'foreign_key': 'id',
      'fields': [
        {
          'description': 'Пункт',
          'name': 'menu_id',
          'type': 'select_from_table',
          'table': 'admin_menu',
          'value_field': 'id',
          'header_field': 'name',
        },
        {
          'description': 'Тип',
          'name': 'type',
          'type': 'text',
          'hide': True,
          'value': 1,
        },
        {
          'description': 'Разрешено',
          'name': 'allowed',
          'type': 'checkbox',
          'value': 1,
          'change_in_slide': 1,
        },
      ],
    },
    {
      'description': 'Разрешения',
      'name': 'rules',
      'type': '1_to_m',
      'table': 'admin_rules',
      'table_id': 'rules_id',
      'foreign_key': 'admin_id',
      'fields': [
        {
          'description': 'Конфиг',
          'name': 'config_name',
          'type': 'select_from_table',
          'table': 'admin_menu',
          'value_field': 'config_name',
          'header_field': 'name',
          'where': "config_name != ''",
          'order': 'name',
        },
        {
          'description': 'url',
          'name': 'url',
          'type': 'text',
        },
        {
          'description': 'Разрешено',
          'name': 'allowed',
          'type': 'checkbox',
          'value': 1,
          'change_in_slide': 1,
        },
        {
          'description': 'Запрещено',
          'name': 'deny',
          'type': 'checkbox',
          'change_in_slide': 1,
        },
      ],
    },
    {
      'description': 'Доступы к проектам',
      'name': 'perm',
      'type': '1_to_m',
      'table': 'project_permission',
      'table_id': 'project_id',
      'foreign_key': 'admin_id',
      'fields': [
        {
          'description': 'Проект',
          'name': 'project_id',
          'type': 'select_from_table',
          'table': 'project',
          'value_field': 'project_id',
          'header_field': 'header',
        },
      ],
    },
    {
      'description': 'Права доступа',
      'name': 'permissions',
      'type': '1_to_m',
      'table': 'admin_permissions',
      'table_id': 'id',
      'foreign_key': 'admin_id',
      'fields': [
        {
          'description': 'Право',
          'name': 'permissions_id',
          'type': 'select_from_table',
          'table': 'permissions',
          'value_field': 'id',
          'header_field': 'header',
          'order': 'sort',
        },
      ],
    },
  ],
}
