form = {
  'work_table': 'capture_setting',
  'work_table_id': 'template_id',
  'title': 'Настройки капчи для шаблона',
  'make_delete': 1,
  'default_find_filter': 'template_id',
  'read_only': 0,
  'tree_use': 0,
  'fields': [
    {
      'description': 'Шаблон',
      'name': 'template_id',
      'type': 'select_from_table',
      'table': 'template',
      'header_field': 'header',
      'value_field': 'template_id',
      'order': 'header',
      'add_description': 'если шаблон отсутствует в списке, значит для него уже созданы настройки',
      'filter_on': True,
    },
    {
      'description': 'Метод вывода',
      'name': 'method',
      'type': 'select_values',
      'values': [
        {'v': 0, 'd': 'Проверочный код'},
        {'v': 1, 'd': 'Пример'},
      ],
    },
    {
      'description': 'width',
      'name': 'width',
      'type': 'text',
      'add_description': 'ширина, px',
    },
    {
      'description': 'height',
      'name': 'height',
      'type': 'text',
      'add_description': 'высота, px',
    },
    {
      'description': 'deg1_from',
      'name': 'deg1_from',
      'type': 'text',
      'add_description': 'угол1, от',
    },
    {
      'description': 'deg1_to',
      'name': 'deg1_to',
      'type': 'text',
      'add_description': 'угол1, до',
    },
    {
      'description': 'deg2_from',
      'name': 'deg2_from',
      'type': 'text',
      'add_description': 'угол2, от',
    },
    {
      'description': 'deg2_to',
      'name': 'deg2_to',
      'type': 'text',
      'add_description': 'угол2, до',
    },
    {
      'description': 'background',
      'name': 'background',
      'type': 'text',
      'add_description': 'цвет фона',
    },
    {
      'description': 'color',
      'name': 'color',
      'type': 'text',
      'add_description': 'цвет шрифта',
    },
    {
      'description': 'fontsize',
      'name': 'fontsize',
      'type': 'text',
      'add_description': 'размер шрифта, px',
    },
    {
      'description': 'chars_count',
      'name': 'chars_count',
      'type': 'text',
      'add_description': 'количество символов в строке ; для примера -- количество символов в выражении (число)',
      'regexp_rules': ['^\\d+$'],
    },
  ],
}
