#!/usr/bin/env python3
"""Генератор JS-схемы для page_constructor (канон — компонент админки CRM).

Конструктор переехал из этого репозитория в админку:
    CrmFreshFront/src/components/svcmsAdmin/page_constructor/
Локальный page_constructor/ — замороженный снимок и не обновляется.

Читает:
  - <admin>/data/schema.json                    (метаданные контролов, ИСТОЧНИК)
  - templates/_shared/contract/blocks.json      (реестр блоков движка, этот репо)

Пишет:
  - <admin>/data/schema.js                       (window.PAGE_CONSTRUCTOR_SCHEMA)

Путь к компоненту админки можно переопределить переменной окружения
SVCMS_CONSTRUCTOR_DIR (см. _constructor_paths.py).

Запуск:
  python3 agent-doc/tools/gen_page_constructor.py
  python3 agent-doc/tools/gen_page_constructor.py --check   # только проверка
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _constructor_paths import CONSTRUCTOR_DIR, SCHEMA_JS, SCHEMA_JSON, require

OUT_SCHEMA_JS = SCHEMA_JS

BANNER = "/* AUTOGENERATED by agent-doc/tools/gen_page_constructor.py — НЕ РЕДАКТИРОВАТЬ ВРУЧНУЮ. */"


def load(path: Path):
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def dump_global(var_name: str, data) -> str:
    payload = json.dumps(data, ensure_ascii=False, indent=2)
    return (
        BANNER
        + "\n"
        + "(function (global) {\n"
        + "  'use strict';\n"
        + f"  global.{var_name} = {payload};\n"
        + "})(typeof window !== 'undefined' ? window : globalThis);\n"
    )


def build_outputs():
    require(SCHEMA_JSON)
    schema = load(SCHEMA_JSON)
    return {OUT_SCHEMA_JS: dump_global("PAGE_CONSTRUCTOR_SCHEMA", schema)}


def main() -> int:
    parser = argparse.ArgumentParser(description="Генератор JS-схемы page_constructor (админка)")
    parser.add_argument("--check", action="store_true", help="не писать, только проверить актуальность")
    args = parser.parse_args()

    outputs = build_outputs()
    stale = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != content:
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")

    if args.check:
        if stale:
            print("УСТАРЕЛО: сгенерированные файлы не совпадают со схемой:")
            for path in stale:
                print(f"  - {path}")
            print("Запусти: python3 agent-doc/tools/gen_page_constructor.py")
            return 1
        print(f"OK: сгенерированная схема конструктора актуальна ({OUT_SCHEMA_JS})")
        return 0

    for path in outputs:
        status = "обновлён" if path in stale else "актуален"
        print(f"  {status}: {path}")
    print(f"  источник: {SCHEMA_JSON}")
    print(f"  компонент: {CONSTRUCTOR_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
