#!/usr/bin/env python3
"""Генератор HTML-разметки форм для превью конструктора (канон — админка).

Частичные шаблоны форм (`templates/<tpl>/block/forms/*_form.html`) не содержат
Jinja (только Vue-директивы), поэтому их можно встроить как есть. Для popup-формы
«Заказать услугу» извлекается только тег <form>.

Пишет <admin>/data/demo/forms.js:  window.PC_FORMS = { "callback": "<html>", ... }
Путь к компоненту админки — SVCMS_CONSTRUCTOR_DIR (см. _constructor_paths.py).

Запуск:
  python3 agent-doc/tools/gen_forms_data.py [--template t1] [--check]
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _constructor_paths import DEMO_DIR

# Шаблон движка (источник частичных форм). Переезд: templates/t1 → движок.
ENGINE_TEMPLATE = Path(os.environ.get(
    "SVCMS_ENGINE_TEMPLATE",
    "/var/www/svcms-async/sites/templates/2026/ds-constructor",
)).expanduser()
OUT_FORMS_JS = DEMO_DIR / "forms.js"
BANNER = "/* AUTOGENERATED by routes/svcmsadmin/page_constructor/tools/gen_forms_data.py — НЕ РЕДАКТИРОВАТЬ. Источник: sites/templates/2026/ds-constructor/block/forms/* */"

FORM_SOURCES = {
    "callback": "block/forms/callback_form.html",
    "consultation": "block/forms/consultation_form.html",
    "calc_cost": "block/forms/calc_cost_form.html",
    "booking": "block/forms/booking_form.html",
    "send_request": "block/forms/send_request_form.html",
    "ask_question": "block/forms/ask_question_form.html",
    "send_review": "block/forms/send_review_form.html",
    "subscribe": "block/forms/subscribe_form.html",
}


def strip_jinja_comment(text: str) -> str:
    return re.sub(r"\{#.*?#\}", "", text, flags=re.S).strip()


def build(template: str):
    base = ENGINE_TEMPLATE
    forms = {}
    for key, rel in FORM_SOURCES.items():
        path = base / rel
        if not path.exists():
            raise FileNotFoundError(f"нет файла {path}")
        forms[key] = strip_jinja_comment(path.read_text(encoding="utf-8"))

    # service_order: только <form> из модалки
    so = base / "block" / "service_order.html"
    if so.exists():
        html = strip_jinja_comment(so.read_text(encoding="utf-8"))
        m = re.search(r"<form\b[^>]*id=\"serviceOrderForm\".*?</form>", html, flags=re.S)
        if m:
            forms["service_order"] = m.group(0)

    content = (
        BANNER + "\n"
        + "(function (global) {\n"
        + "  'use strict';\n"
        + "  global.PC_FORMS = " + json.dumps(forms, ensure_ascii=False, indent=2) + ";\n"
        + "})(typeof window !== 'undefined' ? window : globalThis);\n"
    )
    return OUT_FORMS_JS, content, list(forms.keys())


def main() -> int:
    parser = argparse.ArgumentParser(description="Генератор data/demo/forms.js (админка) из частичных шаблонов форм")
    parser.add_argument("--template", default="t1")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    path, content, keys = build(args.template)
    current = path.read_text(encoding="utf-8") if path.exists() else ""

    if args.check:
        if current != content:
            print(f"УСТАРЕЛО: {path} — запусти gen_forms_data.py")
            return 1
        print(f"OK: {path} актуален ({len(keys)} форм)")
        return 0

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"обновлён: {path} — {len(keys)} форм: {', '.join(keys)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
